services:
  - type: web
    name: mittal-bhojnalya
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn website.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: DJANGO_SETTINGS_MODULE
        value: website.settings
      - key: DEBUG
        value: False
